openapi: 3.0.0
info:
  version: '1.0'
  title: Michigan Hospital Association Opiates of Interest Detector
  description: >-
    This object scans a list of prescriptions and determines if the patient is
    taking an opiate
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
tags:
  - name: KO Endpoints
    description: Opioid Endpoints
servers:
  - url: /99999/10104/1.0
paths:
  /mhaOpiateDetector:
    post:
      tags:
        - KO Endpoints
      description: >-
        This object scans a list of prescriptions and determines if the patient
        is
            taking an opiate
      operationId: mhaOpiateDetector
      requestBody:
        description: RxNorm Semantic Clinical Drug codes for a patient
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/druglist'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  schemas:
    druglist:
      required:
        - rxcuis
      properties:
        rxcuis:
          type: string
          example: '106500,200240,856917,994226,197446,801958'
    output:
      required:
        - result
      properties:
        result:
          type: object
          example: >-
            {"condition_satisfied" : true, "summary" : { "mhaOpiate" : true },
            "detail" : { "106500" : { "mhaOpiate" : false }, "197446" : {
            "mhaOpiate" : false }, "200240" : { "mhaOpiate" : false }, "801958"
            : { "mhaOpiate" : false }, "856917" : { "mhaOpiate" : false },
            "994226" : { "mhaOpiate" : true }}}
