openapi: 3.0.2
info:
  version: '1.0'
  title: Computation of Medication Regimen Complexity Index
  description: >-
    Computing Patient's Medication Regimen Complexity Index based on the
    patient's prescription list
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/mrci/1.0
paths:
  /mrci:
    post:
      description: Medication Regimen Complexity Index
      operationId: mrci
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: >-
                https://demo.kgrid.org/schemas/patientwithrx.yaml#/patientwithprescriptionlist
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericresponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
