openapi: 3.0.0
info:
  version: '1.0'
  title: Opioid and Benzodiazepine Detector
  description: >-
    This object scans a list of prescriptions and determines if the patient is
    at risk greater for drug-induced respiratory depression because of being
    exposed simultaneously to a known dangerous combination of an opioid, a
    benzodiazepine, and a muscle relaxant.
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
servers:
  - url: /99999/10102/1.0
tags:
  - name: KO Endpoints
    description: Opioid and Benzodiazepine Detector Endpoints
paths:
  /opioidbzdDetector:
    post:
      tags:
        - KO Endpoints
      description: >-
        scans a list of a patient's prescriptions and determines if they are
        being exposed simultaneously to a known risky combination of an opioid
        and a benzodiazepine.
      operationId: opioidbzdDetector
      requestBody:
        description: RxNorm Semantic Clinical Drug codes for a patient
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/druglist'
      responses:
        '200':
          description: >-
            identifies if an opioid and benzodiazepine was found, list of rxcui
            and inputs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
components:
  schemas:
    druglist:
      required:
        - rxcuis
      properties:
        rxcuis:
          type: string
          example: '106500,200240,856917,994226,197446,801958'
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: >-
            {condition_satisfied:false,summary:{opioid:false,bzd:false},detail:{}}
